### ISSUE TITLE
Authentication is not working

### ISSUE THREAD

**Issue by Corewala** [evan-goode/mania#12]
Looks like a new TIDAL update broke authentication again:

```
Traceback (most recent call last):
  File "/home/corewala/.local/lib/python3.9/site-packages/mania/tidal.py", line 199, in _refresh
    refresh_response.raise_for_status()
  File "/usr/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://auth.tidal.com/v1/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/corewala/.local/bin/mania", line 8, in <module>
    sys.exit(main())
  File "/home/corewala/.local/lib/python3.9/site-packages/mania/mania.py", line 444, in main
    run()
  File "/home/corewala/.local/lib/python3.9/site-packages/mania/mania.py", line 420, in run
    session.check_valid()
  File "/home/corewala/.local/lib/python3.9/site-packages/mania/tidal.py", line 90, in check_valid
    self._refresh()
  File "/home/corewala/.local/lib/python3.9/site-packages/mania/tidal.py", line 200, in _refresh
    except requests.response.HTTPError as error:
AttributeError: module 'requests' has no attribute 'response'
```

**Comment by evan-goode** [comment]
Could you make sure you're updated to the latest version? `pip3 install --user --upgrade --force-reinstall "https://github.com/evan-goode/mania/archive/master.zip"`
That should fix the `AttributeError` and correctly reauthenticate when trying to refresh returns a 401.

That being said, it does seem like refreshing the OAUTH token doesn't work very often (if at all) and I frequently have to re-pair using the `https://link.tidal.com/XXXXX` link. I'll take a closer look later. Someone mentioned that TIDAL stopped validating CAPTCHAs during login, so I actually might be able to just switch back to the old username/password authentication.

**Comment by Corewala** [comment]
Reinstalled and it seems to be working now. Sorry about that!
